# Generated by Django 4.2.4 on 2023-09-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='x',
            field=models.CharField(default='x', max_length=2),
        ),
    ]
