# Generated by Django 4.2.4 on 2023-09-24 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_x'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='x',
        ),
    ]
